### ISSUE TITLE
Version 0.13 is still set as default

### ISSUE THREAD

**Issue by jvoigtlaender** [lambdatoast/ui-share-elm#4]
... it seems. At least when one follows a link to some piece of code. That makes it unconvenient to use with recent code examples from/on the mailing list.

(I had a look at the source, trying to figure out where the default version is set, so that I could possibly write a pull request. But the source in the repo does not seem to be up to date with respect to what actually runs at http://share-elm.com/. For example, [this line](https://github.com/lambdatoast/ui-share-elm/blob/master/index.html#L48) does contradict what link is actually shown in the live instance of the site.)

**Comment by lambdatoast** [comment]
Sorry for the confusion! This is indeed not the actual codebase for share-elm.com anymore. 
I'm currently rewriting share-elm.com entirely (both server and client sides) using different tech, and I'll open source the whole thing when I'm done with the first working version.
I will fix this issue, though, and I'll update this ticket when it's done. 
Thanks for reporting!

**Comment by lambdatoast** [comment]
Fixed. It was a bug in the DB storage logic. New links should have their version stored correctly.
